# Generated by Django 5.2.5 on 2026-05-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_image'),
    ]

    operations = [
    ]
